### ISSUE TITLE
open a tab based on the users location

### ISSUE THREAD

**Issue by nikolaiwarner** [nikolaiwarner/tabschedule#1]
probably utilizing this:
https://developer.chrome.com/extensions/location

**Comment by luizpericolo** [comment]
Is this related to the timezone of the schedule?

**Comment by nikolaiwarner** [comment]
I'm thinking this would be a feature that allows the user to specify a physical location for a tab and when the user enters that region, the tab appears.  For example, a user might want their tabs related to work open up automatically every time when they arrive at their office.

**Comment by luizpericolo** [comment]
Oh, I see. I'll open another issue then.
