### ISSUE TITLE
Dozens of duplicate tabs open sometimes

### ISSUE THREAD

**Issue by dirvine2** [nikolaiwarner/tabschedule#7]
I use Chrome on a Mac (High Sierra). If my laptop is closed and asleep at a time when tabs are scheduled to open, when I do wake up my laptop I often get dozens of tabs. This morning a couple hundred opened. I had to use Chrome's task manager to close them all and it took several minutes even then.

**Comment by nikolaiwarner** [comment]
Hi @dirvine2! That sounds stressful! I'm not actively developing this extension anymore. Though I'm happy to take a pull request.

At the moment, I would suggest using this extension, which does all that tabschedule does and more:
http://www.tabsnooze.com/
