### ISSUE TITLE
Same Link Schedule

### ISSUE THREAD

**Issue by harunshn** [nikolaiwarner/tabschedule#8]
Hello, 

Can you fix the issues;

* I can't submit different schedules for same link
* Don't have every day, every week, every month, every x day options. 
* Don't have multiply options. 

My case; I want to open a link every day at 9  AM, 11 AM, 3 PM, 5 PM... 
I cant submit same link for multiply schedules. I cant select minutes in time option.

**Comment by nikolaiwarner** [comment]
Hi! I'm not actively developing this extension anymore. Though I'm happy to take a pull request.

At the moment, I would suggest using this extension, which does all that tabschedule does and more:
http://www.tabsnooze.com/
